apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  # Replicas
  BACKEND_REPLICAS: "3"
  FRONTEND_REPLICAS: "3"
  MYSQL_REPLICAS: "1"

  # Database
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/reclamations_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  MYSQL_DATABASE: "reclamations_db"

  # Backend
  SERVER_PORT: "9090"
  BACKEND_URL: "http://backend:9090"

  # Environment
  APP_ENV: "production"
